(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var t3=function(a){a.ea("cardstatechange",a.Ch()&&a.qk()?1:0)},u3=function(a,b){var c=g.Ma(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},IOa=function(a){var b=g.$l(a);
a=g.fm(a);return new g.Ol(b.x,b.y,a.width,a.height)},JOa=function(a){return Math.pow(a,3)},KOa=function(a){return 3*a*a-2*a*a*a},x3=function(a){a=g.Pa(a);
delete v3[a];g.Ge(v3)&&w3&&w3.stop()},MOa=function(){w3||(w3=new g.J(function(){LOa()},20));
var a=w3;a.isActive()||a.start()},LOa=function(){var a=g.Ra();
g.se(v3,function(b){NOa(b,a)});
g.Ge(v3)||MOa()},y3=function(a,b,c,d){g.fr.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.S=b;this.duration=c;this.I=d;this.coords=[];this.progress=this.K=0;this.D=null},NOa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;OOa(a,a.progress);1==a.progress?(a.i=0,x3(a),a.onFinish(),a.Aw()):a.Dc()&&a.dC()},OOa=function(a,b){"function"===typeof a.I&&(b=a.I(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.S[c]-a.u[c])*b+a.u[c]},POa=function(a,b){g.ke.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.i},z3=function(a,b,c,d,e){y3.call(this,b,c,d,e);
this.element=a},A3=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
z3.call(this,a,b,c,d,e)},B3=function(a){g.H.call(this);
this.u=a||window;this.i=[]},C3=function(a){return a.baseUrl||null},D3=function(a,b){return g.Jo(g.tm(a,b,void 0),function(c){return!!c})},QOa=function(a,b,c){function d(W){var ra,sa,Bb,pb=W.hovercardButton;
if(!pb)return null;pb=pb.subscribeButtonRenderer;if(!pb)return null;var zc=f(pb.unsubscribedButtonText),cd=f(pb.subscribedButtonText);if(pb.subscribed){var Ba=f(pb.subscriberCountWithUnsubscribeText);var ac=f(pb.subscriberCountText)}else Ba=f(pb.subscriberCountText),ac=f(pb.subscriberCountWithSubscribeText);var vb=null;return W.signinEndpoint&&(vb=u3(W,"signinEndpoint","webNavigationEndpointData","url"),vb||(vb=null===(Bb=null===(sa=null===(ra=pb.signInEndpoint)||void 0===ra?void 0:ra.commandMetadata)||
void 0===sa?void 0:sa.webCommandMetadata)||void 0===Bb?void 0:Bb.url),!vb)?null:zc&&(cd||vb)?{subscribed:pb.subscribed,subscribeText:zc,subscribeCount:Ba,unsubscribeText:cd,unsubscribeCount:ac,enabled:pb.enabled,signinUrl:vb,classic:W.useClassicSubscribeButton}:null}
function e(W){if(W){var ra=[],sa=W.videoId;sa&&ra.push("v="+sa);(sa=W.playlistId)&&ra.push("list="+sa);(W=W.startTimeSeconds)&&ra.push("t="+W);return"/watch?"+ra.join("&")}}
function f(W){if(!W)return null;var ra=W.simpleText;return ra?ra:W.runs?g.tm(W.runs,function(sa){return sa.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,q=null,r=null,u=null,x=!1,y=null,z=null,E=null,F=null,B=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,q=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,r=f(b.playlistLength);else if("CHANNEL"===h){if(x=u3(l,"browseEndpoint","browseId"))u=x,m="/channel/"+u;n=!1;p="new";(x=!!b.isSubscribe)?y=d(b):z=f(b.subscribersText)}else"WEBSITE"===
h?((E=u3(l,"urlEndpoint","url"))&&(m=E),n=!0,p="new",E=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(F=f(b.productPrice)),b.additionalFeesText&&(B=f(b.additionalFeesText)),(n=u3(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=u3(b,"title","accessibility","accessibilityData","label");var L=b.endpoint?b.endpoint.clickTrackingParams:null,S="";if(b.metadata){var K=f(b.metadata);K&&(S=K)}return{id:"element-"+c,type:h,title:f(b.title),metadata:S,callToAction:f(b.callToAction),RJ:b.image,
iconUrl:E,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:q,playlistLength:r,channelId:u,subscribeButton:y,subscribersText:z,isSubscribe:x,targetUrl:m||null,KS:n,sessionData:L?{itct:L}:null,tX:p,Fu:a?a:null,NS:b.isPlaceholder,impressionUrls:D3(b.impressionUrls||[],C3),BS:D3(b.hovercardShowUrls||[],C3),clickUrls:D3(l.loggingUrls||[],C3),visualElement:g.ry(b.trackingParams),
productPrice:F,additionalFeesText:B}},E3=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:D3(a.impressionUrls||[],C3),elements:D3(a.elements||[],function(d,e){return QOa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.ry(a.trackingParams));return c},F3=function(a){g.VM.call(this,a);
this.B=this.endscreen=null;this.i={};this.D={};this.C=this.u=null;this.K=[];this.X=!0;this.I=0;a=a.V();this.S=g.VE(a)||g.ZE(a);this.events=new g.mD(this);g.I(this,this.events);this.events.T(this.player,g.fA("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.gA("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.wb);this.events.T(window,"focus",this.vW);this.load();var b=g.Og("STYLE");(g.Ag("HEAD")[0]||document.body).appendChild(b);g.je(this,function(){g.Sg(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},ROa=function(a){return a.player.getVideoData().D?"current":a.S?"new":"current"},G3=function(a){return"creator-endscreen-editor"===a.player.V().playerStyle},SOa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=E3(f,ROa(a))));H3(a,f)},
urlParams:{v:c},withCredentials:!0};a.S&&(c.urlParams.ptype="embedded");var d=b.tq;d&&(c.postParams={ad_tracking:d});if(b=g.Jpa(b))if(b=g.Hf(b),b=g.Df(b))a.B=g.Ht(b,c)},H3=function(a,b,c){c=void 0===c?!0:c;
a.player.Ye("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.t(Object.values(a.i)),e=d.next();!e.done;e=d.next())e.value.dispose();a.i={};a.D={};0<a.K.length&&(a.K.forEach(function(l){l.dispose()}),a.K.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&TOa(a);c=[];d=new g.dA(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.V().isMobile||(a.u=new g.V({G:"div",L:"ytp-ce-shadow"}),g.IM(a.player,a.u.element,4),a.C=new g.rL(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=UOa(a,e);if(f){a.i[e.id]=f;a.D[e.id]=e;g.IM(a.player,f.element,4);var h=new g.dA(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);VOa(a,
f,e)}else g.Ey(new g.hw("buildEndscreenElement null",e))}a.player.Bd(c);a.wb()}},TOa=function(a){var b=g.uy(),c=g.vy();
c&&b&&a.endscreen.visualElement&&g.Iy(void 0,c,b,[a.endscreen.visualElement])},UOa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c=a.player.N("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={G:"div",Ga:["ytp-ce-element","ytp-ce-video"],W:{tabindex:"0","aria-label":b.Fu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",W:I3(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",W:{href:J3(a,b.targetUrl),tabindex:"-1"},U:[{G:"div",Ga:["ytp-ce-video-title"].concat(g.la(c)),W:{dir:g.pr(b.title||
"")},ya:b.title},{G:"div",L:"ytp-ce-video-duration",ya:b.videoDuration||void 0}]}]};c=new g.V(a);break;case "PLAYLIST":c=a.player.N("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={G:"div",Ga:["ytp-ce-element","ytp-ce-playlist"],W:{tabindex:"0","aria-label":b.Fu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",W:I3(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",W:{href:J3(a,
b.targetUrl),tabindex:"-1"},U:[{G:"div",Ga:["ytp-ce-playlist-title"].concat(g.la(c)),W:{dir:g.pr(b.title||"")},ya:b.title},{G:"div",L:"ytp-ce-playlist-count",U:[{G:"div",L:"ytp-ce-playlist-icon"},{G:"div",L:"ytp-ce-playlist-count-text",ya:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={G:"div",Ga:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],W:{tabindex:"0","aria-label":b.Fu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},
{G:"div",L:"ytp-ce-expanding-overlay",U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"a",Ga:["ytp-ce-channel-title","ytp-ce-link"],W:{href:J3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.pr(b.title||"")},ya:b.title},b.subscribeButton?{G:"div",L:"ytp-ce-subscribe-container",U:[{G:"div",L:"ytp-ce-channel-subscribe"}]}:
"",b.subscribersText?{G:"div",L:"ytp-ce-channel-subscribers-text",ya:b.subscribersText}:"",b.metadata?{G:"div",Ga:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],ya:b.metadata}:""]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:I3(b)}]};c=new g.V(c);var d=g.Bg(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.M(d,"ytp-ce-subscribe-button");if(a.player.V().isMobile){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.YN(b.subscribeButton.subscribeText,
b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.K.push(e)}break;case "WEBSITE":a={G:"div",Ga:["ytp-ce-element","ytp-ce-website"],W:{tabindex:"0","aria-label":b.Fu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},
{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"div",L:"ytp-ce-website-title",W:{dir:g.pr(b.title||"")},ya:b.title},{G:"div",L:"ytp-ce-website-metadata",ya:b.metadata},{G:"a",Ga:["ytp-ce-website-goto","ytp-ce-link"],W:{href:J3(a,b.targetUrl),target:"_blank",tabindex:"-1"},ya:b.callToAction}]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:I3(b)},{G:"div",
L:"ytp-ce-expanding-icon",W:WOa(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={G:"div",L:"ytp-ce-merchandise-price-container",U:[{G:"div",L:"ytp-ce-merchandise-price",ya:b.productPrice}]},b.additionalFeesText&&c.U.push({G:"div",L:"ytp-ce-merchandise-additional-fees",ya:b.additionalFeesText})),a={G:"div",Ga:["ytp-ce-element","ytp-ce-merchandise"],W:{tabindex:"0","aria-label":b.Fu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",
U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"div",L:"ytp-ce-merchandise-title",W:{dir:g.pr(b.title||"")},ya:b.title},c,{G:"div",L:"ytp-ce-merchandise-metadata",ya:b.metadata},{G:"a",Ga:["ytp-ce-merchandise-goto","ytp-ce-link"],W:{href:J3(a,b.targetUrl),target:"_blank",tabindex:"-1"},ya:b.callToAction}]}]}]}]},
{G:"div",L:"ytp-ce-expanding-image",W:I3(b)},{G:"div",L:"ytp-ce-merchandise-invideo-cta-container",U:[{G:"div",L:"ytp-ce-merchandise-invideo-cta",ya:b.callToAction||void 0}]}]},c=new g.V(a)}b.NS&&g.M(c.element,"ytp-ce-placeholder");return c},I3=function(a){if(a.RJ)var b=a.RJ.thumbnails;
return WOa(b?b[b.length-1].url:null)},WOa=function(a){return a?{style:"background-image: url("+a+")"}:{}},VOa=function(a,b,c){function d(m){m&&(b.Ra("blur",function(){"none"!=m.style.display&&a.X&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.M(b.element,"ytp-ce-force-expand"),K3(a,c.id,!0)):(g.Uq(b.element,"ytp-ce-force-expand"),g.Uq(b.element,"ytp-ce-element-hover"),K3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ra("mouseenter",function(){L3(a,b,c)});
b.Ra("mouseleave",function(){M3(a,b,c)});
a.player.V().isMobile||b.Ra("click",function(){g.M(b.element,"ytp-ce-element-hover")});
b.Ra("click",function(m){XOa(a,c,m)});
b.Ra("keypress",function(m){XOa(a,c,m)});
b.Ra("focus",function(){L3(a,b,c)});
b.Ra("blur",function(){M3(a,b,c)});
b.Ra("touchstart",function(){L3(a,b,c)});
var l=g.Dg("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.Uq(b.element,"ytp-ce-element-hover");g.Uq(b.element,"ytp-ce-force-expand")});
b.Ra("keydown",function(m){a.X=9===m.keyCode&&!m.shiftKey});
d(g.Dg("ytp-sb-subscribe",b.element));d(g.Dg("ytp-sb-unsubscribe",b.element));b.Ra("focus",f);b.Ra("blur",h)},XOa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Sq(d,"ytp-ce-element");){g.Sq(d,"subscribe-label")&&N3(a,b);
if(g.Sq(d,"ytp-ce-channel-subscribe"))return;d=g.Tg(d)}if(!d||g.Sq(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.i[b.id])M3(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.tX)N3(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Hf(J3(a,b.targetUrl)),c=g.Df(c),g.RL(c,void 0,b.sessionData);else{var e=a.player.getVideoData().D,f=function(){var h=J3(a,b.targetUrl),l=b.sessionData,m=g.Qs(h);e&&m&&(m.v||m.list)?a.player.Pj(m.v,l,m.list,!1):
g.QL(h,l)};
N3(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},J3=function(a,b){a=a.player.V();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.xF(a)+b}else return"";return b},L3=function(a,b,c){g.Sq(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.M(b.element,"ytp-ce-element-hover"):a.player.V().isMobile?(new g.J(function(){g.M(b.element,"ytp-ce-element-hover")},200)).start():g.M(b.element,"ytp-ce-element-hover"),O3(a,c.BS),K3(a,c.id,!0))},M3=function(a,b,c){g.Uq(b.element,"ytp-ce-element-hover");
g.Uq(b.element,"ytp-ce-force-expand");K3(a,c.id,!1)},K3=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.t(Object.keys(a.i)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.N(a.i[e].element,"ytp-ce-element-shadow-show",c)},O3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||G3(a))c&&c();else{b=YOa(a,b);var e=0,f=!1,h=new g.J(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.ev(b[a],d)}},N3=function(a,b,c){O3(a,b.clickUrls,c);
(a=g.vy())&&b.KS&&g.Oy(a,b.visualElement)},YOa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(ZOa(b[d],c));return a},ZOa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},$Oa=function(a){return"string"===typeof a?a:""},P3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},aPa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.i=d},Q3=function(a){return a.value?a.value:null},R3=function(a){if(!a)return null;
var b=g.Hf($Oa(a.value));b=g.Df(b);if(!b)return null;var c=P3(a.target,bPa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new aPa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},cPa=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},fPa=function(a){if(!a)return null;
var b=P3(a.type,dPa),c=P3(a.trigger,ePa);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=R3(a?a:null);return b?new cPa(b,c,a):null},S3=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},gPa=function(a,b){return g.Mb(a.action,b,void 0)},hPa=function(a,b){this.context=a;
this.i=b},U3=function(a){return a.customMessage?T3("div","iv-card-message",a.customMessage):""},V3=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{G:"div",L:"iv-card-image",W:{style:a},U:c}},W3=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.t(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(T3("li","",c.value));return{G:"ul",L:"iv-card-meta-info",U:b}},T3=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.pr(c);return{G:a,W:b,ya:c}},iPa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.iy&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.iy+");");c.dir=g.pr(a.customMessage);var d=[{G:"span",ya:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",L:"iv-card-link-icon"}));return{G:"div",Ga:b,W:c,U:d}},X3=function(a,b,c,d){if(d){b=g.t(b);
for(var e=b.next();!e.done;e=b.next())a.i(e.value,d,c.id,c.sessionData,c.tracking.click,5)}},jPa=function(a,b){this.merchant=a;
this.price=b},kPa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},lPa=function(a,b){return b?b:kPa(a)?"current":"new"},Y3=function(a,b){g.H.call(this);
var c=this;this.element=a;this.context=b;this.fb=!1;this.Pa=new Map;this.Va=new Map;this.context.J.addEventListener(g.fA("annotations_module"),function(d){(d=c.Pa.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.gA("annotations_module"),function(d){(d=c.Va.get(d))&&d.apply(c)})},Z3=function(a,b,c,d,e,f,h){a.context.i.Ra(b,"click",function(l){a.eC(c,d,e,f||[],h||0,l)});
a.context.i.Ra(b,"touchstart",function(){a.fb=!1});
a.context.i.Ra(b,"touchmove",function(){a.fb=!0})},mPa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},$3=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
cO:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
eB:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},c4=function(a,b,c){Y3.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Ka=this.kb=this.B=this.ge=!1;this.va=null;this.cards=[];this.jb=this.S=this.Ia=this.D=this.Na=this.i=null;this.ma=[];this.K=this.De=this.Ba=null;this.I=0;this.Aa=new g.J(g.Ja,c.Y.td?4E3:3E3);g.I(this,this.Aa);this.Za=new g.J(g.Ja);g.I(this,this.Za);this.Z=new hPa(c,function(e,f,h,l,m,n){Z3(d,e,f,h,l,m,n)});
this.X=new g.V({G:"div",L:"iv-drawer",W:{id:"iv-drawer"},U:[{G:"div",L:"iv-drawer-header",W:{"aria-role":"heading"},U:[{G:"span",L:"iv-drawer-header-text"},{G:"button",Ga:["iv-drawer-close-button","ytp-button"],W:{"aria-label":"\u0421\u043a\u0440\u044b\u0442\u044c \u043f\u043e\u0434\u0441\u043a\u0430\u0437\u043a\u0438",tabindex:"0"}}]},{G:"div",L:"iv-drawer-content"}]});g.I(this,this.X);this.C=this.X.element;this.Wa=new g.rL(this.X,330);g.I(this,this.Wa);this.ob=g.Dg("iv-drawer-header-text",this.C);
this.u=g.Dg("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.kb&&a4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.kb=d.B)&&b4(d)})},nPa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){a4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){b4(a)});
var c=b.headerText;g.Vg(a.ob,c);a.S&&a.S.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ba=g.ry(b.trackingParams);a.K=g.ry(b.closeTrackingParams);a.De=g.ry(b.iconTrackingParams)},oPa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.kA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:d4(a,c,b,d),sponsored:!1,tracking:$3(d,e,d.command),El:d.trackingParams?g.ry(d.trackingParams):null,Qi:e.trackingParams?
g.ry(e.trackingParams):null,De:f&&f.trackingParams?g.ry(f.trackingParams):null,imageUrl:e4(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.kA(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,iy:null,title:d.title?g.kA(d.title):"",customMessage:d.callToAction?g.kA(d.callToAction):"",url:d.command.urlEndpoint.url?R3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};f4(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.kA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:d4(a,c,b,d),sponsored:!1,tracking:$3(d,e,d.endpoint),El:d.trackingParams?g.ry(d.trackingParams):null,Qi:e.trackingParams?g.ry(e.trackingParams):null,De:f&&f.trackingParams?
g.ry(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.kA(d.customText):null,profileImageUrl:e4(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.kA(d.channelName):"",metaInfo:[d.subscriberCountText?g.kA(d.subscriberCountText):""],url:R3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};
f4(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.kA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:d4(a,c,b,d),sponsored:!1,tracking:$3(d,e,d.action),El:d.trackingParams?g.ry(d.trackingParams):
null,Qi:e.trackingParams?g.ry(e.trackingParams):null,De:f&&f.trackingParams?g.ry(f.trackingParams):null,wx:e4(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.kA(d.customMessage):null,playlistVideoCount:g.kA(d.playlistVideoCount),title:d.playlistTitle?g.kA(d.playlistTitle):"",metaInfo:[d.channelName?g.kA(d.channelName):"",d.videoCountText?g.kA(d.videoCountText):""],url:R3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:mPa(d.action)})};f4(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.videoInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.kA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:d4(a,c,b,d),sponsored:!1,tracking:$3(d,e,d.action),El:d.trackingParams?g.ry(d.trackingParams):null,Qi:e.trackingParams?g.ry(e.trackingParams):null,De:f&&f.trackingParams?g.ry(f.trackingParams):
null,wx:e4(d.videoThumbnail.thumbnails,258).url,videoDuration:d.lengthString?g.kA(d.lengthString):null,customMessage:d.customMessage?g.kA(d.customMessage):null,title:d.videoTitle?g.kA(d.videoTitle):"",metaInfo:[d.channelName?g.kA(d.channelName):"",d.viewCountText?g.kA(d.viewCountText):""],isLiveNow:!!d.badge,url:R3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:mPa(d.action)})};f4(a,b)}a.I++},e4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===
a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},d4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},qPa=function(a,b){if(b=pPa(a,b))b===a.i&&(a.i=null),a.J.removeCueRange(b.card.id),g.Sg(b.XC),g.Tb(a.cards,b),a.ly(),g4(a)},a4=function(a,b,c){if(!a.B){a.Wa.show();
a.Na=new g.J(function(){g.M(a.context.J.getRootNode(),g.oT.IV_DRAWER_OPEN)},0);
a.Na.start();a.va=g.Fu(a.u,"mousewheel",function(h){a.Aa.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.vy();d&&a.Ba&&a.K&&g.My(d,[a.Ba,a.K]);b={TRIGGER_TYPE:b};for(var e=g.t(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.EL||(f.EL=!0,rPa(a.context.logger,f.card.tracking.impression,b)),d&&g.My(d,[f.card.El]);t3(a.J);c&&(a.D=new g.J(function(){a.Ia=a.S;a.jb.focus()},330),a.D.start())}},b4=function(a){a.B&&(a.Wa.hide(),g.Gu(a.va),a.va=null,g.Uq(a.context.J.getRootNode(),g.oT.IV_DRAWER_OPEN),a.B=!1,t3(a.J),a.D&&a.D.stop(),a.D=new g.J(function(){a.Ia&&(a.Ia.focus(),a.Ia=null)},330),a.D.start())},
tPa=function(a){g.Tq(a.element,[g.oT.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.IM(a.J,a.C,5);sPa(a);a.S=g.Dg("ytp-cards-button",a.J.getRootNode());a.jb=g.Dg("iv-drawer-close-button",a.C);a.ge=!0},sPa=function(a){var b=g.Dg("iv-drawer-close-button",a.C);
a.context.i.Ra(b,"click",a.pR,a);a.context.i.Ra(a.u,"touchend",function(){a.Aa.start()});
a.context.i.Ra(a.u,"scroll",a.BR,a);a.context.u.subscribe("onHideControls",function(){a.Ka=!0});
a.context.u.subscribe("onShowControls",function(){a.Ka=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Ka=g.Sq(a.J.getRootNode(),"ytp-autohide")});
a.ma.push(g.lv("iv-button-shown",a.VS,a));a.ma.push(g.lv("iv-button-hidden",a.US,a));a.ma.push(g.lv("iv-teaser-shown",a.VP,a));a.ma.push(g.lv("iv-teaser-hidden",a.WS,a));a.ma.push(g.lv("iv-teaser-clicked",a.UP,a))},f4=function(a,b){a.ge||tPa(a);
qPa(a,b.id);var c=uPa(a,b);if(c){var d={card:b,XC:c.element,EL:!1},e=vPa(a,d);g.Zb(a.cards,e,0,d);c.Da(a.u,e);a.ly();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.i=d,g4(a),wPa(a,d),a4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&xPa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){xPa(a,d)}),g4(a))}},uPa=function(a,b){switch(b.type){case "simple":a=a.Z;
var c=b.displayDomain?{G:"div",L:"iv-card-image-text",ya:b.displayDomain}:void 0;var d=iPa(b);c={G:"div",Ga:["iv-card"],U:[{G:"a",L:"iv-click-target",W:{href:b.url?Q3(b.url)||"":""},U:[V3(b.imageUrl,c),{G:"div",L:"iv-card-content",U:[T3("h2",void 0,b.title),d]}]}]};c=new g.V(c);X3(a,g.Cg("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.Z,c={G:"div",Ga:["iv-card","iv-card-channel"],U:[{G:"a",Ga:["iv-click-target"],W:{href:Q3(b.url)||"","data-ytid":b.channelId},U:[V3(b.profileImageUrl),
{G:"div",L:"iv-card-content",U:[U3(b),{G:"h2",L:"iv-card-primary-link",ya:b.title},W3(b)]}]}]},c=new g.V(c),X3(a,g.Cg("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.Z,c={G:"div",Ga:["iv-card","iv-card-playlist"],U:[{G:"a",L:"iv-click-target",W:{href:Q3(b.url)||""},U:[V3(b.wx,{G:"div",L:"iv-card-image-overlay",U:[{G:"span",L:"iv-card-playlist-video-count",ya:b.playlistVideoCount}]}),{G:"div",L:"iv-card-content",U:[U3(b),T3("h2","iv-card-primary-link",b.title),W3(b)]}]}]},c=new g.V(c),
X3(a,g.Cg("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.Z;var e=!g.Qb(b.offers);c=["iv-card"];d="";var f=iPa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({G:"div",L:"iv-card-offer-price",ya:f.price}),f.merchant&&e.push({G:"div",L:"iv-card-offer-merchant",ya:f.merchant}),f={G:"div",U:e});e=b.url?Q3(b.url)||"":"";c={G:"div",Ga:c,W:{tabindex:"0"},U:[{G:"a",Ga:["iv-card-image","iv-click-target"],W:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{G:"div",L:"iv-card-content",U:[b.sponsored?{G:"div",L:"iv-card-sponsored",U:["\u0420\u0435\u043a\u043b\u0430\u043c\u0430",{G:"div",L:"iv-ad-info-container",U:[{G:"div",L:"iv-ad-info",ya:"{{adInfo}}"},{G:"div",L:"iv-ad-info-icon-container",U:[{G:"div",L:"iv-ad-info-icon"},{G:"div",L:"iv-ad-info-callout"}]}]}]}:"",{G:"a",L:"iv-click-target",W:{href:e},U:[T3("h2",d,b.title),f]}]}]};c=new g.V(c);d=g.Og("span");g.Vg(d,"\u042d\u0442\u043e \u043a\u043e\u043d\u0442\u0435\u043a\u0441\u0442\u043d\u0430\u044f \u0440\u0435\u043a\u043b\u0430\u043c\u0430. \u0415\u0435 \u043f\u043e\u043a\u0430\u0437 \u043c\u043e\u0436\u0435\u0442 \u043e\u043f\u043b\u0430\u0447\u0438\u0432\u0430\u0442\u044c\u0441\u044f \u043f\u0440\u043e\u0434\u0430\u0432\u0446\u043e\u043c.");
c.kd(d,"adInfo");X3(a,g.Cg("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.Z,d=b.videoDuration?{G:"span",L:"iv-card-video-duration",ya:b.videoDuration}:void 0,f=b.isLiveNow?{G:"span",Ga:["yt-badge","yt-badge-live"],ya:"\u0421\u0415\u0419\u0427\u0410\u0421 \u0412 \u041f\u0420\u042f\u041c\u041e\u041c \u042d\u0424\u0418\u0420\u0415"}:null,e={G:"div",Ga:["iv-card","iv-card-video"],U:[{G:"a",L:"iv-click-target",W:{href:(null===(c=b.url)||void 0===c?void 0:Q3(c))||""},U:[V3(b.wx,
d),{G:"div",L:"iv-card-content",U:[U3(b),T3("h2","iv-card-primary-link",b.title),W3(b),f]}]}]},c=new g.V(e),X3(a,g.Cg("iv-click-target",c.element),b,b.url),c;default:return null}},vPa=function(a,b){if(0===a.cards.length)return 0;
a=g.Nb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},yPa=function(a){return a.i?"productListing"===a.i.card.type:g.um(a.cards,function(b){return"productListing"===b.card.type})},g4=function(a){g.N(a.J.getRootNode(),"ytp-cards-shopping-active",yPa(a))},xPa=function(a,b){if(!g.Sq(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.i!==b){var c=g.vy(),d=a.i?a.i.card.De:a.De;
c&&d&&g.Ny(c,[d]);a.i=b;g4(a)}if(c="none"!=a.element.style.display)a.context.J.V().N("html5_enable_single_video_vod_ivar_on_pacf")||2!==a.context.J.getPresentingPlayerType()?(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=1===c||3===c||d):c=1===a.context.J.getAdState();c&&b.card.teaserDurationMs&&a.J.ot(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.Za.isActive()||((!a.B||!a.Aa.isActive()&&a.Ka)&&wPa(a,b),a.Za.start(910+b.card.teaserDurationMs))}},
wPa=function(a,b){a.X.zb?(b=new y3([0,
a.u.scrollTop],[0,b.XC.offsetTop],600,KOa),a.context.B.Ra(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Ra(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.IK(a.X,!0),a.u.scrollTop=b.XC.offsetTop,g.IK(a.X,!1))},h4=function(a){return a.i&&a.i.card?a.i.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},pPa=function(a,b){return g.Mb(a.cards,function(c){return c.card.id===b})},i4=function(a,b,c){Y3.call(this,a,b);
this.annotation=c;this.isActive=!1},zPa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},j4=function(a,b,c){i4.call(this,a,b,c);
this.u=null;this.K=!1;this.B=null;this.C=!1;this.i=this.I=this.D=null},APa=function(a,b){var c=void 0===c?0:c;
var d=IOa(b).width;g.Yl(b,d);c=new A3(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,JOa);g.I(a,c);a.context.B.Ra(c,"begin",function(){g.gm(b,!0)});
c.play()},DPa=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
Ga:["iv-branding-context-name"],ya:b.channel_name}),d=a.createElement({G:"div",Ga:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.i=new g.YN(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.J),a.i.Da(d));var f=a.createElement({G:"div",Ga:["iv-branding-context-subscribe-caret"]}),h=a.createElement({G:"div",Ga:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.gm(h,!1);var l=a.createElement({G:"div",Ga:["branding-context-container-outer"]});l.appendChild(h);g.Rl(l,"right",b.image_width+"px");a.element.appendChild(l);a.B=new g.J(function(){BPa(a,h,l)},500);
g.I(a,a.B);a.context.i.Ra(a.element,"mouseover",function(){CPa(a,h,l,f,b.image_height)});
a.context.i.Ra(a.element,"mouseout",function(){a.B.start()})}},CPa=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.fm(b);a.i||(b.style.width=g.Xl(f.width,!0),c.style.width=g.Xl(f.width,!0));g.Rl(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Rl(d,"right","1px");a.C=!0;g.gm(b,!0);a.D=new g.J(function(){g.M(this.element,"iv-branding-active")},0,a);
a.D.start()}},BPa=function(a,b,c){g.Uq(a.element,"iv-branding-active");
a.I=new g.J(function(){g.gm(b,!1);a.i||(c.style.width=g.Xl(0,!0))},250);
a.I.start();a.C=!1},EPa=function(a,b,c,d,e,f,h){this.i=a;
this.B=b;this.Y=c;this.videoData=d;this.logger=e;this.J=f;this.u=h},k4=function(a,b,c){i4.call(this,a,b,c);
var d=this;this.S=this.isCollapsed=this.X=!1;this.I=5E3;this.u=this.B=this.i=this.C=null;this.K=this.createElement({G:"div",Ga:["iv-promo-contents"]});this.D=new g.J(function(){d.i.setAttribute("aria-hidden","true");g.gm(d.B,!1);g.gm(d.u,!0)},700,this);
g.I(this,this.D)},FPa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","\u041f\u0440\u043e\u0434\u0432\u0438\u0436\u0435\u043d\u0438\u0435");a.element.tabIndex=0;var e=a.annotation.Yd(),f=b.image_url;if(f){var h=a.createElement({G:"div",Ga:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",W:{src:f,
"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=a.createElement({G:"span",L:"iv-promo-video-duration",ya:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",L:"iv-promo-playlist-length",ya:b.playlist_length.toString()}),h.appendChild(f));e&&Z3(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",L:"iv-promo-txt"}),g.bg(f,Q3(e)),a.i=f):a.i=a.createElement({G:"div",L:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=
a.createElement({G:"p",U:[{G:"strong",ya:b.text_line_1}]});var m=a.createElement({G:"p",U:[{G:"span",L:"iv-promo-link",ya:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",Ga:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",Ga:["iv-button","iv-promo-button"],U:[{G:"span",L:"iv-button-content",ya:f}]});var p=a.createElement({G:"div",L:"iv-promo-button-container"});p.appendChild(f);e&&Z3(a,a.element,e,a.annotation.id,
b.session_data,void 0,c)}g.M(a.i,"iv-click-target");e&&Z3(a,a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",U:[{G:"span",ya:b.text_line_1}]}),m=a.createElement({G:"p",U:[{G:"strong",ya:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",Ga:["yt-badge","iv-promo-badge-live"],ya:"\u0421\u0415\u0419\u0427\u0410\u0421 \u0412 \u041f\u0420\u042f\u041c\u041e\u041c \u042d\u0424\u0418\u0420\u0415"})),g.M(a.i,"iv-click-target"),e&&Z3(a,a.i,
e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.i.appendChild(l);m&&a.i.appendChild(m);a.K.appendChild(a.i);p&&a.K.appendChild(p);c=a.createElement({G:"div",L:"iv-promo-actions"});a.u=a.createElement({G:"button",Ga:["iv-promo-expand","ytp-button"]});a.u.title="\u0420\u0430\u0437\u0432\u0435\u0440\u043d\u0443\u0442\u044c";a.context.i.Ra(a.u,"click",function(q){l4(a,5E3,q)});
c.appendChild(a.u);g.gm(a.u,!1);a.context.i.Ra(a.element,"mouseover",a.hS,a);a.context.i.Ra(a.element,"mouseout",a.gS,a);a.context.i.Ra(a.element,"touchend",function(q){l4(a,5E3,q)});
a.B=a.createElement({G:"button",Ga:["iv-promo-close","ytp-button"]});a.B.title="\u0417\u0430\u043a\u0440\u044b\u0442\u044c";a.context.i.Ra(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.cS:a.bS,a);c.appendChild(a.B);g.Tq(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.K);a.element.appendChild(c)},l4=function(a,b,c){c.stopPropagation();
GPa(a);HPa(a,b);a.i.focus()},IPa=function(a){a.isCollapsed||a.S||a.C||(g.M(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},GPa=function(a){a.D.stop();
a.isCollapsed&&(g.Vq(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.gm(a.u,!1),g.gm(a.B,!0))},HPa=function(a,b){a.C||(a.C=g.Ch(function(){m4(this);
IPa(this)},b,a))},m4=function(a){a.C&&(g.C.clearTimeout(a.C),a.C=null)},JPa=function(a){this.J=a},rPa=function(a,b,c){b&&(c?n4(a,b.map(function(d){return g.Cq(d,c)})):n4(a,b))},n4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.t(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.ev(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},o4=function(a){g.VM.call(this,a);
var b=this;this.X=!1;this.loadNumber=0;this.K={};this.logger=new JPa(this.player);this.D=new g.mD(this);this.I=this.B=null;this.events=new g.mD(this);this.S=this.i=null;this.ma=[];g.I(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.ea("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.ea("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.ea("onShowControls")});
this.D.T(this.player,"resize",function(d){b.ea("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.ea("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.WP,this);this.subscribe("resize",this.hA,this);this.player.V().S.subscribe("vast_info_card_add",this.TM,this);g.I(this,this.events);this.Z=this.createElement({G:"div",L:"video-custom-annotations"});this.u=new g.V({G:"div",Ga:["ytp-player-content","ytp-iv-player-content"]});g.I(this,this.u);g.IM(this.player,this.u.element,4);this.u.hide();this.C=new g.V({G:"div",Ga:["ytp-iv-video-content"]});g.I(this,this.C);a=this.createElement({G:"div",L:"video-annotations"});
a.appendChild(this.Z);this.C.element.appendChild(a);this.Fq()&&this.load();var c=this.createElement({G:"style"});(g.Ag("HEAD")[0]||document.body).appendChild(c);g.je(this,function(){g.Sg(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},KPa=function(a){a=a.createElement({G:"div",
Ga:["annotation","annotation-type-custom"]});g.gm(a,!1);return a},LPa=function(a,b){b=!b.isCued()&&!g.U(b,1024);
g.IK(a.u,b);g.IK(a.C,b)},MPa=function(a,b,c){a.X=!0;
a.I=g.Ht(b,c)},NPa=function(a,b){for(var c={},d=g.t(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Na(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(NPa(a,e))}return c},QPa=function(a){var b=a.player.getVideoData();
if(b.Va){var c=a.player.V().S.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.bt(h)&&h.responseXML?h.responseXML:null)&&p4(a,h)}};
g.Wu()&&(d.onFinish=OPa(a,d.onFinish));d.postParams={ic_only:"1"};PPa(d,c);a.X=!0;g.Ht(b.Va,d)}}},PPa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.Qu&&(a.postParams.ic_coll=b.Qu);b.uy&&(a.postParams.ic_xml=b.uy);b.zx&&(a.postParams.ic_track=b.zx)},RPa=function(a){var b=new g.V({G:"div"});
g.gm(b.element,!1);var c=new c4(a.player,b.element,q4(a));g.I(c,b);b.Da(a.u.element);c.ex();return c},q4=function(a){if(!a.S){var b=new B3(a);
g.I(a,b);var c=new g.ek(a);g.I(a,c);a.S=new EPa(b,c,a.player.V(),a.player.getVideoData(),a.logger,a.player,a.oe)}return a.S},p4=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.vy();if(e){var f=g.uy();f&&g.Iy(void 0,e,f,[g.ry(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=NPa(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=P3(f.type,SPa),p=P3(f.style,TPa),q=$Oa(f.data),r=0!==q.length?JSON.parse(q):{};var u=f.action;f=fPa;if(null==u)var x=null;else if(g.Ma(u)){l=[];for(var y=g.t(u),z=y.next();!z.done;z=y.next()){var E=f(z.value);
E&&l.push(E)}x=l}else{var F=f(u);x=F?[F]:[]}e=m&&n?new S3(m,n,p,x,r):null}else e=null}catch(ra){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var B=KPa(f),L=null;switch(l.type){case "branding":if(f.player.V().Cb)break;f.u.element.appendChild(B);L=new j4(B,q4(f),l);break;case "promotion":g.IM(f.player,B,4),L=new k4(B,q4(f),l)}L&&L.ex();if(f=L)g.I(a,f),a.K[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.i||(a.i=RPa(a),g.I(a,a.i));if("card"===e.type){c=a.i;var S=e&&e.data&&e.data.card_type;
f=e.data;if(S)switch(l=f.tracking||{},l={impression:l.impression,click:l.click,close:l.close,cO:l.teaser_impression,eB:l.teaser_click},B=f.tracking_params||{},L=null,S){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,El:B.card?g.ry(B.card):null,Qi:B.teaser?g.ry(B.teaser):null,De:B.icon?g.ry(B.icon):null,
channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:R3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};f4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,El:B.card?g.ry(B.card):
null,Qi:B.teaser?g.ry(B.teaser):null,De:B.icon?g.ry(B.icon):null,wx:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:R3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};f4(c,e);break;case "productListing":f.signin_url&&(L=R3({target:"current",value:f.signin_url}));S=[];for(var K=f.offers||[],W=0;W<K.length;W++)S.push(new jPa(g.qg(K[W].merchant),g.qg(K[W].price)));e={id:e.id,
timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,El:B.card?g.ry(B.card):null,Qi:B.teaser?g.ry(B.teaser):null,De:B.icon?g.ry(B.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,iy:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:
null,url:R3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),Gba:L,Fba:f.signin_title?f.signin_title:void 0,Eba:f.signin_message?f.signin_message:void 0,offers:S};f4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,El:B.card?g.ry(B.card):null,Qi:B.teaser?g.ry(B.teaser):
null,De:B.icon?g.ry(B.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,iy:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:R3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};f4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||
!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,El:B.card?g.ry(B.card):null,Qi:B.teaser?g.ry(B.teaser):null,De:B.icon?g.ry(B.icon):null,wx:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:R3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})},f4(c,e)}}else nPa(a.i,e);c=!0}}c&&(t3(a.player),a.hA())},UPa=function(a,b){var c=!1;
a.i||(a.i=RPa(a),g.I(a,a.i));for(var d=g.t(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(oPa(a.i,e.cardRenderer),c=!0);c&&(c=a.i,d=b.headerText?g.kA(b.headerText):"",g.Vg(c.ob,d),c.S&&c.S.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ba=b.trackingParams?g.ry(b.trackingParams):null,c.K=b.closeButton.infoCardIconRenderer.trackingParams?g.ry(b.closeButton.infoCardIconRenderer.trackingParams):null,c.De=b.icon.infoCardIconRenderer.trackingParams?
g.ry(b.icon.infoCardIconRenderer.trackingParams):null,t3(a.player),a.hA())},VPa=function(a,b,c,d,e){if(!a.player.V().Cb){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new cPa("openUrl","click",new aPa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.kA(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.kA(b.subscriberCountText))):(b.subscriberCountText&&(e=g.kA(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.kA(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.kA(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.kA(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new S3(c,"branding","branding",f,d);l=KPa(a);a.u.element.appendChild(l);f=new j4(l,q4(a),f);f.ex();g.I(f,f);a.K[c]=f}},OPa=function(a,b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];
a.isDisposed()||a.ma.push(g.bv.Qf(function(){b.apply(null,g.la(d))}))}},WPa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.BM.prototype.ot=g.ca(17,function(a,b){var c=g.jN(this.vb());c&&c.ot(a,b)});
var v3={},w3=null;g.Sa(y3,g.fr);g.k=y3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.i)this.progress=0,this.coords=this.u;else if(this.Dc())return!1;x3(this);this.startTime=a=g.Ra();-1==this.i&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.eA();this.wi("play");-1==this.i&&this.wi("resume");this.i=1;var b=g.Pa(this);b in v3||(v3[b]=this);MOa();NOa(this,a);return!0};
g.k.stop=function(a){x3(this);this.i=0;a&&(this.progress=1);OOa(this,this.progress);this.wi("stop");this.Aw()};
g.k.pause=function(){this.Dc()&&(x3(this),this.i=-1,this.wi("pause"))};
g.k.xa=function(){0==this.i||this.stop(!1);this.wi("destroy");y3.le.xa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.dC=function(){this.wi("animate")};
g.k.wi=function(a){this.dispatchEvent(new POa(a,this))};
g.Sa(POa,g.ke);g.Sa(z3,y3);z3.prototype.C=g.Ja;z3.prototype.dC=function(){this.C();z3.le.dC.call(this)};
z3.prototype.Aw=function(){this.C();z3.le.Aw.call(this)};
z3.prototype.eA=function(){this.C();z3.le.eA.call(this)};
g.Sa(A3,z3);A3.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.v(B3,g.H);B3.prototype.Ra=function(a,b,c,d){c=(0,g.D)(c,d||this.u);a=g.Fu(a,b,c);this.i.push(a);return a};
B3.prototype.Lz=function(a,b,c,d){c=(0,g.D)(c,d||this.u);a=g.Ou(a,b,c);this.i.push(a);return a};
B3.prototype.hc=function(a){g.Gu(a);g.Tb(this.i,a)};
B3.prototype.xa=function(){g.Gu(this.i);this.i.length=0;g.H.prototype.xa.call(this)};g.v(F3,g.VM);g.k=F3.prototype;g.k.load=function(){g.VM.prototype.load.call(this);if(!G3(this)){var a=g.Kpa(this.player.getVideoData());a?(a=E3(a,ROa(this)),H3(this,a,!1)):SOa(this)}};
g.k.unload=function(){H3(this,null);this.B&&(this.B.abort(),this.B=null);g.VM.prototype.unload.call(this)};
g.k.kf=function(a,b){return G3(this)?"loadCustomEndscreenRenderer"===a?(a=E3(b,"new"),H3(this,a),!0):null:null};
g.k.getOptions=function(){return G3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.wb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<XPa.length;f++){var h=Math.abs(b.width-XPa[f]);if(-1===e||d>=h)e=f,d=h}d=YPa[e];this.u&&g.Rl(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.i[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.em(e.element,Math.round(h.width*a.width),f);g.Yl(e.element,m,n);g.Vq(e.element,ZPa);m=h.left+h.width/2;h=h.top+l/2;g.M(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Vq(e.element,YPa);g.M(e.element,d);(e=g.Bg(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.Rl(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())O3(this,this.endscreen.impressionUrls),(a=g.vy())&&this.endscreen.visualElement&&g.Jy(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.i[a],c=this.D[a];g.M(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.M(b,"ytp-ce-shown");O3(this,c.impressionUrls);(b=g.vy())&&g.Jy(b,c.visualElement,void 0);this.player.V().u&&this.player.Ma("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.i[a];g.Uq(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Uq(b,"ytp-ce-shown");this.player.V().u&&this.player.Ma("endscreenelementhidden",a)}};
g.k.vW=function(a){var b=this;a.target===window&&(new g.J(function(){for(var c=g.t(Object.values(b.i)),d=c.next();!d.done;d=c.next())g.Vq(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var XPa=[346,426,470,506,570,640,853,1280,1920],YPa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),ZPa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var bPa={g1:"current",a7:"new"};var dPa={CLOSE:"close",t7:"openUrl",SUBSCRIBE:"subscribe"},ePa={tZ:"click",CLOSE:"close",L2:"hidden",S8:"rollOut",T8:"rollOver",I9:"shown"};S3.prototype.Yd=function(){var a=gPa(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var TPa={LY:"anchored",QO:"branding",CHANNEL:"channel",f1:"cta",O2:"highlightText",P3:"label",PLAYLIST:"playlist",l8:"popup",R9:"speech",SUBSCRIBE:"subscribe",j$:"title",VIDEO:"video",waa:"website"},SPa={QO:"branding",gZ:"card",C1:"drawer",N2:"highlight",t5:"marker",v8:"promotion",TEXT:"text",Caa:"widget"};g.v(Y3,g.H);g.k=Y3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.dA(a,b,{id:c,namespace:"annotations_module"});d&&this.Pa.set(a,d);e&&this.Va.set(a,e);this.context.J.Bd([a])};
g.k.ex=function(){this.context.u.subscribe("resize",this.ly,this)};
g.k.eC=function(a,b,c,d,e,f){if(this.fb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Sg(this.element)};
g.k.ly=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=Q3(a);if(f){var h=lPa(f,a.target),l=function(){a.i&&e.context.J.pauseVideo();var m=e.context.videoData.D||!1,n=g.Qs(f||"");m&&n&&(n.v||n.list)?e.context.J.Pj(n.v,b,n.list,!1):g.RL(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);n4(this.context.logger,c,l,d);kPa(f)||(c=g.vy(),d=b.itct,c&&d&&g.Oy(c,g.ry(d)))}};
g.k.xa=function(){this.Pa.clear();this.Va.clear();g.H.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.I(this,a);return a.element};g.v(c4,Y3);g.k=c4.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.fm(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.ly=function(){var a=this.isAvailable();g.gm(this.element,a);g.N(this.context.J.getRootNode(),g.oT.IV_DRAWER_ENABLED,a);t3(this.J)};
g.k.destroy=function(){this.J.ot(!1);try{this.J.getRootNode().removeChild(this.C)}catch(a){}g.mv(this.ma);g.Gu(this.va);this.Na&&this.Na.dispose();this.D&&this.D.dispose();Y3.prototype.destroy.call(this)};
g.k.pR=function(){if(this.B){n4(this.context.logger,h4(this).tracking.close);var a=g.vy();a&&this.K&&g.Oy(a,this.K);b4(this)}};
g.k.BR=function(){g.N(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.VS=function(){var a=g.vy(),b=h4(this);b=b?b.De:this.De;a&&b&&g.My(a,[b])};
g.k.US=function(){var a=g.vy(),b=h4(this);b=b?b.De:this.De;a&&b&&g.Ny(a,[b])};
g.k.VP=function(){var a=h4(this);n4(this.context.logger,a.tracking.cO);var b=g.vy();b&&a&&g.My(b,[a.Qi,a.De])};
g.k.WS=function(){var a=g.vy(),b=h4(this);a&&b&&g.Ny(a,[b.Qi])};
g.k.UP=function(a){var b=h4(this),c=g.vy();this.i?a?(a=this.context.logger,n4(a,b.tracking.eB),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Qi&&g.Oy(c,b.Qi)):(a=this.context.logger,n4(a,b.tracking.eB),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.De&&g.Oy(c,b.De)):(a=this.context.logger,n4(a,b.tracking.eB),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.De&&g.Oy(c,this.De))};g.v(i4,Y3);i4.prototype.ex=function(){Y3.prototype.ex.call(this);zPa(this)};
i4.prototype.show=function(){Y3.prototype.show.call(this);var a=g.vy(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.My(a,[g.ry(b.itct)])};
i4.prototype.hide=function(){Y3.prototype.hide.call(this);var a=g.vy(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Ny(a,[g.ry(b.itct)])};g.v(j4,i4);
j4.prototype.show=function(){if(!this.isActive){i4.prototype.show.call(this);if(!this.K){g.M(this.element,"iv-branding");var a=this.annotation.data;this.u=this.createElement({G:"img",Ga:["branding-img","iv-click-target"],W:{"aria-label":"\u041b\u043e\u0433\u043e\u0442\u0438\u043f \u043a\u0430\u043d\u0430\u043b\u0430",src:a.image_url,width:a.image_width,height:a.image_height}});g.gm(this.u,!1);var b=this.createElement({G:"div",Ga:["branding-img-container"]});b.appendChild(this.u);this.element.appendChild(b);(b=
this.annotation.Yd())&&Z3(this,this.u,b,this.annotation.id,a.session_data);DPa(this,a);this.K=!0}g.gm(this.element,!0);this.isActive=!0;this.u&&APa(this,this.u)}};
j4.prototype.hide=function(){this.isActive&&(i4.prototype.hide.call(this),g.gm(this.element,!1),this.isActive=!1)};
j4.prototype.destroy=function(){this.i&&(this.i.dispose(),this.i=null);i4.prototype.destroy.call(this)};g.v(k4,i4);g.k=k4.prototype;g.k.show=function(){this.isActive||(i4.prototype.show.call(this),this.X||(FPa(this),this.X=!0),g.gm(this.element,!0),g.Ch(function(){g.Uq(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,m4(this),GPa(this),HPa(this,this.I))};
g.k.hide=function(){this.isActive&&(g.M(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.eC=function(a,b,c,d,e,f){return this.isCollapsed?!1:i4.prototype.eC.call(this,a,b,c,d,e,f)};
g.k.hS=function(a){this.S=!0;l4(this,500,a)};
g.k.gS=function(){this.S=!1;IPa(this)};
g.k.bS=function(a){a.stopPropagation();this.hide()};
g.k.cS=function(a){a.stopPropagation();m4(this);this.isCollapsed=!0;g.M(this.element,"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();i4.prototype.destroy.call(this)};g.v(o4,g.VM);g.k=o4.prototype;g.k.kf=function(a,b){if(!WPa(this.player.V().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.U1(b))&&p4(this,a),!0;case "removeCustomAnnotationById":return b&&this.i&&(qPa(this.i,b),t3(this.player)),!0}return null};
g.k.getOptions=function(){return WPa(this.player.V().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Fq=function(){var a=this.player.V(),b=this.player.getVideoData();return b.D&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.NK||a.S.get(b.videoId)||g.KG(b)||g.LG(b)?!0:!1};
g.k.hA=function(){if(this.C){var a=this.player.bb().getVideoContentRect(!0);g.em(this.C.element,a.width,a.height);g.Yl(this.C.element,a.left,a.top)}if(this.i){var b=this.player.lj();a=this.i;b=b.width;g.N(a.C,"iv-drawer-small",426>=b);g.N(a.C,"iv-drawer-big",1280<=b)}};
g.k.WP=function(a){LPa(this,a.state);g.U(a.state,2)&&(this.Ch()&&this.qk()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.ot(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.I=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.bt(h)&&h.responseXML?h.responseXML:null)&&(p4(b,h),g.M(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.VM.prototype.load.call(this);LPa(this,this.player.yb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.Wu()&&(a=OPa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.I=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.V().S.get(d);f&&PPa(e,f);f=f&&(f.uy||f.Qu);if(!c.Xo||f)c.Va?MPa(this,c.Va,e):(this.B=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.B));
g.IM(this.player,this.C.element,4);this.hA();(f=g.KG(c))&&UPa(this,f);(f=g.LG(c))&&f.featuredChannel&&VPa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Va&&(this.B&&(this.player.removeEventListener("videodatachange",this.B),this.B=null),MPa(this,b.Va,a))};
g.k.unload=function(){this.player.Ye("annotations_module");for(var a=g.t(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.S=null;this.i&&(this.i.destroy(),this.i=null,t3(this.player));this.X=!1;this.I&&(this.I.abort(),this.I=null);this.K={};this.u.hide();g.VM.prototype.unload.call(this);this.C.detach();this.B&&(this.player.removeEventListener("videodatachange",this.B),this.B=null)};
g.k.TM=function(a){a===this.player.getVideoData().videoId&&(this.loaded?QPa(this):this.load())};
g.k.Ch=function(){return!!this.i&&this.i.isAvailable()};
g.k.qk=function(){this.Ch();return!!this.i&&this.i.B};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Ch();this.i&&(a?c?a4(this.i,c,b):a4(this.i,"YOUTUBE_DRAWER_AUTO_OPEN",b):b4(this.i))};
g.k.ot=function(a,b){this.player.ea(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.xa=function(){this.player.V().S.unsubscribe("vast_info_card_add",this.TM,this);g.Uq(this.player.getRootNode(),g.oT.IV_DRAWER_OPEN);for(var a=this.ma,b=0,c=a.length;b<c;b++)g.bv.oi(a[b]);this.ma.length=0;g.VM.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.I(this,a);return a.element};g.UM("annotations_module",o4);g.UM("creatorendscreen",F3);})(_yt_player);
