import Head from 'next/head';

import { useContext, useEffect, useState } from 'react';

import { useWindowResize } from 'shared';

import { AnimateStartContext, SmoothScrollContext } from 'shared/context';

import ContactForm from 'components/ContactForm';

import { StyledContactUs } from 'styles/contactUs';

export default function HowItWorks() {
  // eslint-disable-next-line no-unused-vars
  const [isTabletMode, setIsTabletMode] = useState(null);
  const { width } = useWindowResize();

  const { gsapScroll } = useContext(SmoothScrollContext);
  const { isAnimationFinished } = useContext(AnimateStartContext);

  const gsap = gsapScroll?.gsap;

  useEffect(() => {
    if (isAnimationFinished) {
      gsap?.to('.content-start', {
        opacity: 1,
        y: 0,
        duration: 0.8,
        stagger: 0.2,
      });
    }
  }, [gsap, isAnimationFinished]);

  useEffect(() => {
    if (width === 0) return;
    setIsTabletMode(width < 1024);
  }, [width]);

  return (
    <>
      <Head>
        <title>Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <StyledContactUs className="contact-us">
        <div className="content-container content-container--contact">
          <span className="contact-us__pre-title content-start">Have some questions?</span>
          <h2 className="section-title content-start">Contact us</h2>
          <ContactForm />
        </div>
      </StyledContactUs>
    </>
  );
}
