import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';

import { getClassNames, useWindowResize } from 'shared';

import placeholderBlogImage from 'assets/images/placeholder-blog.jpg';

import SuggestedArticles from 'components/SuggestedArticles';

import { StyledSingleArticle } from 'styles/singleArticle';
import { useContext, useEffect, useState } from 'react';
import { AnimateStartContext, SmoothScrollContext } from 'shared/context';

const currentTags = ['Health', 'Postage', 'Medicine', 'Man', 'Testosterone', 'Health', 'Postage', 'Medicine',
	'Testosterone', 'Health', 'Postage', 'Medicine'];

export default function SingleArticle() {
	const [isTabletMode, setIsTabletMode] = useState(null);
	const [pageTitle, setPageTitle] = useState('Article page');

	const router = useRouter();
	const { slug } = router.query;

	const { gsapScroll } = useContext(SmoothScrollContext);
	const { isAnimationFinished } = useContext(AnimateStartContext);

	const { width } = useWindowResize();

	useEffect(() => {
		if (slug) {
			setPageTitle(slug.charAt(0).toUpperCase() + slug.slice(1));
		}
	}, [slug]);

	useEffect(() => {
		if (width === 0) return;
		setIsTabletMode(width < 1024);
	}, [width]);

	useEffect(() => {
		if (isTabletMode && width !== 0) {
			document.querySelector('.article-content__image').setAttribute('data-scroll', '');
		}
	}, [width, isTabletMode]);

	const gsap = gsapScroll?.gsap;

	useEffect(() => {
		if (isAnimationFinished) {
			gsap?.to(
				'.content-start',
				{
					opacity: 1,
					y: 0,
					duration: 0.8,
					stagger: 0.3,
				}
			);
		}
	}, [gsap, isAnimationFinished]);

	return (
		<>
			<Head>
				<title>{pageTitle}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<StyledSingleArticle>
				<div
					className="section-title-wrapper"
				>
					<h1 className="content-start">{slug}</h1>
				</div>
				<div className="article-content">
					<div className="content-container content-container--single-article">
						<h2 className="content-start">Getting older isn't always a walk in the park. But that doesn't
							mean it has to be an uphill battle.
						</h2>
						<p className="content-start">
							Postage was created to deliver a higher standard of wellbeing for men
							of every age. Through continuous, consultative care, sophisticated solutions,
							and a streamlined service model, we make it easy to rediscover the best version of you.
							<br />
							<br />
							Postage was created to deliver a higher standard of wellbeing for men of every
							age. Through continuous, consultative care, sophisticated solutions, and a
							streamlined service model, we make it easy to rediscover the best version of
							you.Postage was created to deliver a higher standard of wellbeing for men of
							every age. Through continuous, consultative care, sophisticated solutions, and
							a streamlined service model, we make it easy to rediscover the best version of you.
							Postage was created to deliver a higher standard of wellbeing for men of every age.
							Through continuous, consultative care, sophisticated solutions, and a streamlined
							service model, we make it easy to rediscover the best version of you.
						</p>
						<Image
							priority
							src={placeholderBlogImage.src}
							width={placeholderBlogImage.width}
							height={placeholderBlogImage.height}
							alt="placeholder"
							className={getClassNames(
								'article-content__image',
								isTabletMode ? 'fadeIn' : 'content-start'
							)}
						/>
						<span className="article-content__image-caption fadeIn" data-scroll>
							Postage was created to deliver a higher standard.
						</span>
						<div className="article-content__text-content flex-between fadeIn" data-scroll>
							<div className="text-content__left">
								<h2 className="one-size">
									Getting older isn't always a walk in the park. But that doesn't mean it
									has to be an uphill battle.
								</h2>
							</div>
							<div className="text-content__right">
								<p className="fadeIn" data-scroll>
									Postage was created to deliver a higher standard of wellbeing for men of every age.
									Through continuous, consultative care, sophisticated solutions, and a
									streamlined service model,
									we make it easy to rediscover the best version of you.Postage was created
									to deliver a higher
									standard of wellbeing for men of every age.
								</p>
							</div>
						</div>
						<p className="fadeIn" data-scroll>
							<strong>Postage was created to deliver a higher standard of
								wellbeing for men of every age.
							</strong>
							Through continuous, consultative care, sophisticated solutions,
							and a streamlined service model, we make it easy to rediscover the best version of you.
							Postage was created to deliver a higher standard of wellbeing

							For men of every age. Through continuous, consultative care, sophisticated solutions,
							and a streamlined service model, we make it easy to rediscover the best version of you.
							Postage was created to deliver a higher standard of wellbeing for men of every age.
							Through continuous, consultative care, sophisticated solutions, and a streamlined
							service model,
							we make it easy to rediscover the best version of you.Postage was created to deliver
							a higher
							standard of wellbeing for men of every age.
						</p>
						<div className="article-content__tags fadeIn" data-scroll>
							{currentTags.map((tag, i) => (
								<span
									key={i}
									className={getClassNames(
										'article-content__tags__core',
										i === 5 && 'active'
									)}
								>
									{tag}
								</span>
							))}
						</div>
					</div>
				</div>
				<SuggestedArticles isYourArticles />
			</StyledSingleArticle>
		</>
	);
}
