/* eslint-disable newline-per-chained-call */
/* eslint-disable react/no-array-index-key */
import Head from 'next/head';

// Sanity Config
import { sanityClient } from 'lib/sanity.server';
import { homePageQuery } from 'lib/sanity.queries';

// sections
import Hero from 'modules/Home/Hero';
import Benefits from 'modules/Home/Benefits';
import Assessment from 'modules/Home/Assessment';
import WhyChoosePostage from 'modules/Home/WhyChoosePostage';
import ThePostageWay from 'modules/Home/ThePostageWay';
import PatientTestimonials from 'modules/Home/PatientTestimonials';
import StopActingYourAge from 'modules/Home/StopActingYourAge';

export default function Home({ pageData }) {
  const sectionsData = pageData?.sections;

  return (
    <>
      <Head>
        <title>Postage Health</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero data={sectionsData.hero} />

      <Benefits data={sectionsData.benefits} />

      <Assessment data={sectionsData.ctaOne} />

      <ThePostageWay data={sectionsData.thePostageWay} />

      <WhyChoosePostage data={sectionsData.whyChoosePostage} />

      <PatientTestimonials data={sectionsData.patientTestimonials} />

      <StopActingYourAge data={sectionsData.ctaTwo} />
    </>
  );
}

export const getStaticProps = async () => {
  const pageData = await sanityClient.fetch(homePageQuery);

  return {
    props: { pageData },
  };
};
